// Generated by zerobufCxx.py
#include "heartbeat.h"
#include <zerobuf/jsoncpp/json/json.h>
#include <iostream>

namespace zeq
{
namespace vocabulary
{
template< class Alloc >
bool HeartbeatBase< Alloc >::readJSON( const std::string& json )
{
    Json::Value dict;
    if( !_parseJSON( json, dict ))
        return false;

    return true;
}


template class HeartbeatBase< ::zerobuf::NonMovingAllocator >;
}
}
