// Generated by zerobufCxx.py
#include "selections.h"
#include <zerobuf/jsoncpp/json/json.h>
#include <iostream>

namespace zeq
{
namespace hbp
{
template< class Alloc >
typename SelectedIDsBase< Alloc >::Ids SelectedIDsBase< Alloc >::getIds()
{
    return Ids( getAllocator( ));
}

template< class Alloc >
typename SelectedIDsBase< Alloc >::ConstIds SelectedIDsBase< Alloc >::getIds() const
{
    return ConstIds( getAllocator( ));
}

template< class Alloc >
void SelectedIDsBase< Alloc >::setIds( uint32_t const * value, size_t size )
{
    _setZerobufArray( value, size * sizeof( uint32_t ), 0 );
}

template< class Alloc >
std::string SelectedIDsBase< Alloc >::getIdsString() const
{
    const uint8_t* ptr = getAllocator()->template getDynamic< const uint8_t >( 0 );
    return std::string( ptr, ptr + getAllocator()->template getItem< uint64_t >( 12 ));
}

template< class Alloc >
void SelectedIDsBase< Alloc >::setIds( const std::string& value )
{
    _setZerobufArray( value.c_str(), value.length(), 0 );
}


template< class Alloc >
bool SelectedIDsBase< Alloc >::readJSON( const std::string& json )
{
    Json::Value dict;
    if( !_parseJSON( json, dict ))
        return false;

    if( dict.isMember( "ids" ))
        std::cout << "ids" << ':' << dict[ "ids" ].toStyledString() << std::endl;
    return true;
}

template< class Alloc >
SelectedIDsBase< Alloc >::SelectedIDsBase()
    : zerobuf::Zerobuf( new Alloc( 20, 1 ))
{}


template< class Alloc >
SelectedIDsBase< Alloc >::SelectedIDsBase( const SelectedIDsBase& from )
    : zerobuf::Zerobuf( new Alloc( *static_cast< const Alloc* >( from.getAllocator( ))))
{}

template< class Alloc >
SelectedIDsBase< Alloc >& SelectedIDsBase< Alloc >::operator = ( const SelectedIDsBase& rhs )
{
    ::zerobuf::Zerobuf::operator = ( rhs );
    return *this;
}

template< class Alloc >
template< class T > void SelectedIDsBase< Alloc >::_setZerobufArray( const T* data, const size_t size, const size_t arrayNum )
{
    void* array = getAllocator()->updateAllocation( arrayNum, size );
    ::memcpy( array, data, size );
}


template class SelectedIDsBase< ::zerobuf::NonMovingAllocator >;
template< class Alloc >
typename ToggleIDRequestBase< Alloc >::Ids ToggleIDRequestBase< Alloc >::getIds()
{
    return Ids( getAllocator( ));
}

template< class Alloc >
typename ToggleIDRequestBase< Alloc >::ConstIds ToggleIDRequestBase< Alloc >::getIds() const
{
    return ConstIds( getAllocator( ));
}

template< class Alloc >
void ToggleIDRequestBase< Alloc >::setIds( uint32_t const * value, size_t size )
{
    _setZerobufArray( value, size * sizeof( uint32_t ), 0 );
}

template< class Alloc >
std::string ToggleIDRequestBase< Alloc >::getIdsString() const
{
    const uint8_t* ptr = getAllocator()->template getDynamic< const uint8_t >( 0 );
    return std::string( ptr, ptr + getAllocator()->template getItem< uint64_t >( 12 ));
}

template< class Alloc >
void ToggleIDRequestBase< Alloc >::setIds( const std::string& value )
{
    _setZerobufArray( value.c_str(), value.length(), 0 );
}


template< class Alloc >
bool ToggleIDRequestBase< Alloc >::readJSON( const std::string& json )
{
    Json::Value dict;
    if( !_parseJSON( json, dict ))
        return false;

    if( dict.isMember( "ids" ))
        std::cout << "ids" << ':' << dict[ "ids" ].toStyledString() << std::endl;
    return true;
}

template< class Alloc >
ToggleIDRequestBase< Alloc >::ToggleIDRequestBase()
    : zerobuf::Zerobuf( new Alloc( 20, 1 ))
{}


template< class Alloc >
ToggleIDRequestBase< Alloc >::ToggleIDRequestBase( const ToggleIDRequestBase& from )
    : zerobuf::Zerobuf( new Alloc( *static_cast< const Alloc* >( from.getAllocator( ))))
{}

template< class Alloc >
ToggleIDRequestBase< Alloc >& ToggleIDRequestBase< Alloc >::operator = ( const ToggleIDRequestBase& rhs )
{
    ::zerobuf::Zerobuf::operator = ( rhs );
    return *this;
}

template< class Alloc >
template< class T > void ToggleIDRequestBase< Alloc >::_setZerobufArray( const T* data, const size_t size, const size_t arrayNum )
{
    void* array = getAllocator()->updateAllocation( arrayNum, size );
    ::memcpy( array, data, size );
}


template class ToggleIDRequestBase< ::zerobuf::NonMovingAllocator >;
}
}
